# Generated by Django 4.2.6 on 2024-02-27 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('subcategoryname', models.CharField(max_length=50)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.category')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('imageid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='--Not Defined--', max_length=100)),
                ('url', models.ImageField(upload_to='images')),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_download', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('categoryid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.category')),
                ('subcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
