# Generated by Django 4.2.6 on 2024-02-28 08:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_category_subcategory_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlistId', models.AutoField(primary_key=True, serialize=False)),
                ('ImageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.img')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentDT', models.DateTimeField(default=datetime.datetime.now)),
                ('PaymentAmount', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('OrderDetailsId', models.AutoField(primary_key=True, serialize=False)),
                ('ImageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.img')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderDT', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=50)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('followId', models.AutoField(primary_key=True, serialize=False)),
                ('followerId', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartId', models.AutoField(primary_key=True, serialize=False)),
                ('ImageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.img')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auctionId', models.AutoField(primary_key=True, serialize=False)),
                ('createdDT', models.DateTimeField(default=datetime.datetime.now)),
                ('AuctionAmount', models.IntegerField()),
                ('Description', models.TextField()),
                ('AuctionStartDate', models.DateField(auto_now_add=True)),
                ('AuctionEndDate', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('ImageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.img')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('AlbumId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('createDT', models.DateTimeField(default=datetime.datetime.now)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
