# Generated by Django 5.0.2 on 2024-03-04 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_wishlist_payment_orderdetails_order_follow_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('likeid', models.AutoField(primary_key=True, serialize=False)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.img')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
