# Generated by Django 5.0.2 on 2024-03-06 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.img')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
