# Generated by Django 5.0.2 on 2024-03-10 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='orderId',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='profiles.order'),
        ),
    ]
