# Generated by Django 5.0.2 on 2024-03-10 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_orderdetails_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.order'),
        ),
    ]
