# Generated by Django 4.2.6 on 2024-03-14 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_orderdetails_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.album'),
        ),
    ]
