# Generated by Django 4.2.6 on 2024-03-15 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_img_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='AuctionEndDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 19, 25, 44, 179221)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Ended', 'Ended')], default='Active', max_length=50),
        ),
    ]
