# Generated by Django 4.2.6 on 2024-03-15 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_auction_auctionenddate_alter_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='AuctionEndDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 19, 42, 28, 842631)),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bidid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_time', models.DateTimeField(default=datetime.datetime.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.img')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
