# Generated by Django 5.0.2 on 2024-03-18 19:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auction_winner_alter_auction_auctionenddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='AuctionEndDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 22, 1, 29, 52, 793813)),
        ),
        migrations.CreateModel(
            name='AuctionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_payment_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
