# Generated by Django 5.0.2 on 2024-03-18 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_auction_auctionenddate_auctionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='highest_bid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='AuctionEndDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 22, 2, 34, 22, 36773)),
        ),
    ]
