# Generated by Django 5.0.2 on 2024-03-21 09:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auction_highest_bid_amount_auction_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='AuctionEndDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 24, 14, 49, 9, 218534)),
        ),
        migrations.CreateModel(
            name='PastOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(default=datetime.datetime.now)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.auction')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.img')),
                ('past_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_owner', to='profiles.userprofile')),
            ],
        ),
    ]
