# Generated by Django 5.0.2 on 2024-03-21 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_auction_auctionenddate_pastowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastowner',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='AuctionEndDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 24, 19, 51, 38, 280334)),
        ),
    ]
