from django.urls import path, include
from . import views

urlpatterns = [
    path('settings/',views.profile_settings),
    path('profile/',views.profile),
    path('explore/',views.loadExplore),
    path('',views.profileHomePage,name='profile_home_page'),
    path('profile/<str:username>',views.profile_view,name='profile'),
    path('createStory/',views.createStory),
    path('createPost/',views.createPost),
    path('search/', views.search_images, name='search_images'),
    path('imageForm/',views.loadImgForm),
    path("imagesUpd/",views.UpdImage),
    path("addWishlist/<int:imageid>/",views.addToWishlist,name='add_to_wishlist'),
    path("removeWishlist/<int:imageid>/",views.removeWishlist,name='remove_wishlist'),
    path("removeCart/<int:imageid>/",views.removeCart,name='remove_cart'),
    path("addCart/<int:imageid>/",views.addToCart,name='add_to_cart'),
    path("wishlist/",views.wishlist,),
    path("cart/",views.cart,),
    path("shop/",views.shop),
    path('imageinfo/<int:imageid>/',views.imageInfo,name="image_info"),
    path("insertLike/",views.insertLike,name="addlike"),
    path("deleteLike/",views.deleteLike,name="dellike"),
    path("addComment/",views.addCommnet,name="addComm"),
    path('checkout/',views.loadCheckout),
    path('proceed-to-pay/',views.razorpaycheck),
    path('place-order/',views.place_order),
    path('myBuy/',views.myBuy),
    path('mylike/',views.myLike),
    path('mysale/',views.my_sales),
    path('analytics/<int:image_id>/', views.analytics, name='analytics'),
    path('download/<int:image_id>/', views.download_image, name='download_image'),
    path('createAlbum/',views.createAlubms),
    path('albums/', views.all_albums, name='all_albums'),
    path('albums/<int:album_id>/', views.album_detail, name='album_detail'),
    path('auction/',views.displayAuction),
    path('createAuction/', views.create_auction, name='create_auction'),
    path('detauction', views.auction_details),
    path('follow/', views.follow_toggle, name='follow_toggle'),
    path('create_auction/<int:image_id>/', views.create_auction_page, name='create_auction_page'),
    path('process-payment/', views.process_payment, name='process_payment'),
    # path('place_bid/', views.place_bid, name='place_bid'),
    path('update_auction_status/', views.update_auction_status, name='update_auction_status'),
]